==> log/autorestart.log <==
2020-03-03T16:45:19.289206Z     [INFO] (default#8611) the mfserv seems to be ok and does not need to be restarted
tail: log/cronlog : fichier tronqué
usage: plugin_wrapper [-h] [--cwd] [--empty]
                      [--do-not-add-plugin-dir-to-python-path]
                      [--add-extra-dir-to-python-path ADD_EXTRA_DIR_TO_PYTHON_PATH]
                      [--add-extra-dir-to-node-path ADD_EXTRA_DIR_TO_NODE_PATH]
                      [--bash-cmds] [--plugins-base-dir PLUGINS_BASE_DIR]
                      PLUGIN_NAME COMMAND_AND_ARGS [COMMAND_AND_ARGS ...]
plugin_wrapper: error: unrecognized arguments: -e --shell
usage: plugin_wrapper [-h] [--cwd] [--empty]
                      [--do-not-add-plugin-dir-to-python-path]
                      [--add-extra-dir-to-python-path ADD_EXTRA_DIR_TO_PYTHON_PATH]
                      [--add-extra-dir-to-node-path ADD_EXTRA_DIR_TO_NODE_PATH]
                      [--bash-cmds] [--plugins-base-dir PLUGINS_BASE_DIR]
                      PLUGIN_NAME COMMAND_AND_ARGS [COMMAND_AND_ARGS ...]
plugin_wrapper: error: unrecognized arguments: -e --shell=~/apicvf_django/
usage: plugin_wrapper [-h] [--cwd] [--empty]
                      [--do-not-add-plugin-dir-to-python-path]
                      [--add-extra-dir-to-python-path ADD_EXTRA_DIR_TO_PYTHON_PATH]
                      [--add-extra-dir-to-node-path ADD_EXTRA_DIR_TO_NODE_PATH]
                      [--bash-cmds] [--plugins-base-dir PLUGINS_BASE_DIR]
                      PLUGIN_NAME COMMAND_AND_ARGS [COMMAND_AND_ARGS ...]
plugin_wrapper: error: unrecognized arguments: -e -s=~/apicvf_django/
python: can't open file 'manage.py': [Errno 2] No such file or directory
python: can't open file 'manage.py': [Errno 2] No such file or directory
